if (NOT DEFINED PLUGIN_DISPLAY_NAME)
	set(PLUGIN_DISPLAY_NAME ${PLUGIN_NAME})
endif (NOT DEFINED PLUGIN_DISPLAY_NAME)
if (NOT DEFINED PLUGIN_DESCRIPTION)
	set(PLUGIN_DESCRIPTION "${PLUGIN_DISPLAY_NAME}")
endif (NOT DEFINED PLUGIN_DESCRIPTION)

include("${CMAKE_SOURCE_DIR}/src/make/config.cmake")
include("${CMAKE_SOURCE_DIR}/src/translations/languages.cmake") 

set(PLUGIN_${PLUGIN_NAME} YES CACHE BOOL "Enable ${PLUGIN_NAME} plugin")

set(IS_ENABLED ${PLUGIN_${PLUGIN_NAME}})

if (IS_ENABLED)
	include_directories("${CMAKE_SOURCE_DIR}/src"
		"${CMAKE_BINARY_DIR}/src/plugins/${PLUGIN_NAME}"
		".")
	add_definitions(-DQT_PLUGIN -DQT_SHARED)

	add_translations(TRANSLATIONS ${PLUGIN_NAME} ${HEADERS} ${SOURCES} ${UIS})
	if (OS2)
		add_library(${PLUGIN_NAME} STATIC ${SOURCES} ${HEADERS} ${UIS} ${TRANSLATIONS})
	else()
		add_library(${PLUGIN_NAME} SHARED ${SOURCES} ${HEADERS} ${UIS} ${TRANSLATIONS})
	endif()
	if (OS2)
		# Keep the logical target name for dependencies, but use the qmake
		# TARGET_SHORT value for the OS/2 8.3 library filename.
		set(OS2_PROJECT_FILE "${CMAKE_CURRENT_SOURCE_DIR}/${PLUGIN_NAME}.pro")
		if (EXISTS "${OS2_PROJECT_FILE}")
			file(STRINGS "${OS2_PROJECT_FILE}" OS2_TARGET_SHORT
				REGEX "^os2:[ 	]*TARGET_SHORT[ 	]*=")
		endif (EXISTS "${OS2_PROJECT_FILE}")
		if (OS2_TARGET_SHORT)
			string(REGEX REPLACE "^os2:[ 	]*TARGET_SHORT[ 	]*=[ 	]*" "" OS2_TARGET_SHORT "${OS2_TARGET_SHORT}")
		else (OS2_TARGET_SHORT)
			foreach(OS2_PLUGIN_OUTPUT_NAME ${OS2_PLUGIN_OUTPUT_NAMES})
				string(REGEX MATCH "^${PLUGIN_NAME}=(.*)$" OS2_PLUGIN_OUTPUT_MATCH "${OS2_PLUGIN_OUTPUT_NAME}")
				if (OS2_PLUGIN_OUTPUT_MATCH)
					set(OS2_TARGET_SHORT "${CMAKE_MATCH_1}")
				endif (OS2_PLUGIN_OUTPUT_MATCH)
			endforeach(OS2_PLUGIN_OUTPUT_NAME)
		endif (OS2_TARGET_SHORT)
		if (OS2_TARGET_SHORT)
			set_target_properties(${PLUGIN_NAME} PROPERTIES OUTPUT_NAME "${OS2_TARGET_SHORT}")
		endif (OS2_TARGET_SHORT)
	endif (OS2)
	set_target_properties(${PLUGIN_NAME} PROPERTIES
		LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/plugins"
		RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/plugins")
	target_link_libraries(${PLUGIN_NAME} PRIVATE
		${VACUUM_UTILS_NAME}
		Qt6::Core Qt6::Gui Qt6::Widgets Qt6::Network Qt6::Xml Qt6::Sql
		${ADD_LIBS})
	if (WIN32)
		install(TARGETS ${PLUGIN_NAME}
			RUNTIME DESTINATION "${INSTALL_PLUGINS}"
			COMPONENT ${PLUGIN_NAME})
	endif (WIN32)
	if (OS2)
		install(TARGETS ${PLUGIN_NAME}
			RUNTIME DESTINATION "${INSTALL_PLUGINS}"
			COMPONENT ${PLUGIN_NAME})
	endif (OS2)
endif (IS_ENABLED)

if (${PLUGIN_NAME}_IS_ESSENTIAL)
	set(PLUGIN_GROUP essential_plugins)
else (${PLUGIN_NAME}_IS_ESSENTIAL)
	set(PLUGIN_GROUP optional_plugins)
endif (${PLUGIN_NAME}_IS_ESSENTIAL)

set(ALL_PLUGINS ${ALL_PLUGINS} ${PLUGIN_NAME} PARENT_SCOPE)
set(${PLUGIN_NAME}_DEPENDENCIES ${PLUGIN_DEPENDENCIES} PARENT_SCOPE)

cpack_add_component(${PLUGIN_NAME}
	DISPLAY_NAME "${PLUGIN_DISPLAY_NAME}"
	DESCRIPTION "${PLUGIN_DESCRIPTION}"
	GROUP ${PLUGIN_GROUP}
	DEPENDS ${VACUUM_UTILS_NAME} ${PLUGIN_DEPENDENCIES})
